@host = 127.0.0.1:10083
@clientId = admin
@clientSecret = 123456
@username = admin
@password = 123456

### 建立一組Token
# @name token

POST /oauth/token?grant_type=password&username={{username}}&password={{password}}&scope=read HTTP/1.1
Host: {{host}}
Authorization: Basic {{clientId}}:{{clientSecret}}

### 確認Token的細節

@accessToken = {{token.response.body.access_token}}
@refreshToken = {{token.response.body.refresh_token}}

# @name check_token

POST /oauth/check_token?token={{accessToken}} HTTP/1.1
Host: {{host}}

### 刷新Token

# @name refresh_token

POST /oauth/token?grant_type=refresh_token&refresh_token={{refreshToken}}&scope=read HTTP/1.1
Host: {{host}}
Authorization: Basic {{clientId}}:{{clientSecret}}

###

# @name jwks

GET /.well-known/jwks.json HTTP/1.1
Host: {{host}}

###

# @name introspect

POST /introspect?token={{accessToken}} HTTP/1.1
Host: {{host}}

### 查詢所有用戶

# @name find_all_user

GET /user HTTP/1.1
Host: {{host}}
Authorization: {{accessToken}}

### 查詢用戶

# @name find_user

GET /user/{{username}} HTTP/1.1
Host: {{host}}
Authorization: {{accessToken}}

### 註冊用戶

# @name register_user

POST /user/register HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
    "userName":"tony02",
    "password":"123456",
    "phone":"",
    "email":""
}

### 用戶修改密碼

# @name change_password

PATCH /user/{{username}} HTTP/1.1
Host: {{host}}
Authorization: {{accessToken}}
Content-Type: application/json

{
    "oldPassword":"123456",
    "newPassword":"123456"
}

### 

# @name logout
DELETE /oauth/logout?username={{username}}&clientId={{clientId}}
Host: {{host}}

###