export const AuthActionTypes = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    LOGOUT: 'USERS_LOGOUT',
    SET_LANGUAGE : 'SET_LANGUAGE',
    SET_MENU_LIST : 'SET_MENU_LIST',
};
