version: "3.7"
services:
  auth-gateway:
    image: ${IMAGE_NAME}
    extra_hosts:
      live-streaming-video: 172.20.111.185
    deploy:
      placement:
        constraints:
          - "node.labels.gateway == true"
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
    ports:
      - "10077:10077"
    volumes:
      - gateway_log:/opt/logs/gateway/
    environment:
      - PROFILE_ACTIVE=dev
    networks:
      - authnetwork
volumes:
  gateway_log:
networks:
  authnetwork:
    external:
      name: authnetwork
