version: "3.7"
services:
  auth-server:
    image: ${IMAGE_NAME}
    deploy:
      placement:
        constraints:
          - "node.labels.auth == true"
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
    environment:
      - PROFILE_ACTIVE=dev
    ports:
      - "10083:10083"
    networks:
      - authnetwork

networks:
  authnetwork:
    external:
      name: authnetwork
