version: "3.7"
services:
  auth-server:
    image: ${IMAGE_NAME}
    extra_hosts:
      auth-postgres: 172.20.111.184
    deploy:
      placement:
        constraints:
          - "node.labels.auth == true"
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
    ports:
      - "10083:10083"
    networks:
      - srsnetwork

networks:
  srsnetwork:
    external:
      name: srsnetwork
