version: "3.7"
services:
  auth-postgres:
    # follow Azure PostgreSQL version
    image: "postgres:13.1-alpine"
    restart: "always"
    volumes:
      - auth-postgres-storage:/var/lib/postgresql/data
      - ./init/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
      - ./init/auth-client.sql:/tmp/auth-client.sql
      - ./init/auth-rbac.sql:/tmp/auth-rbac.sql
    ports:
      - "25432:5432"
    environment:
      # Default Account: postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - authnetwork

networks:
  authnetwork:
    external:
      name: authnetwork

volumes:
  auth-postgres-storage:
